theme:
  logo: images/likelion_kor_logo_renew.svg
  name: material
edit_uri: edit/main/docs
extra_css:
- stylesheets/custom.css
extra_javascript:
- javascripts/custom.js
markdown_extensions:
- admonition
- codehilite
- toc:
    permalink: true
nav:
- 홈: index.md
- 교안:
  - Git:
    - Git 01: git/git_01.md
  - Java:
    - Java-01 준비: java/java-01_준비.md
- 체크리스트: []
- FAQ: faq.md
repo_name: GitHub
repo_url: https://github.com/carami/backend-guide
site_description: 멋쟁이 사자처럼의 백엔드 부트캠프 강의페이지
site_name: 멋쟁이 사자처럼 백엔드 부트캠프
